# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
  adapters:
    media_adapter:
      local:
        directory: '%kernel.project_dir%/var/storage/%kernel.environment%'
        lazy: true
        permissions:
          dir:
            private: 0700
            public: 0755
          file:
            private: 0600
            public: 0644

  filesystems:
    mediafs:
      adapter: media_adapter
      cache: ~
      alias: ~
      mount: mediafs
      visibility: public
