easy_admin:
  entities:
    TemplateFolder:
      class: App\Entity\Folder\TplFolder
      label: Folders
      list:
        fields:
          - {property: 'label'}
          - {property: 'description'}
      form:
        fields:
          - {property: 'label'}
          - {property: 'description'}
          - {property: 'tplQuestionnaires', label: 'Questionnaires', type_options: {by_reference: false}}
          - {property: 'calendars', 'label': 'Calendars', type_options: {by_reference: false}}

