easy_admin:
  entities:
    TemplateQuestionnaire:
      class: App\Entity\Questionnaire\TplQuestionnaire
      label: Questionnaires
      list:
        fields:
          - {property: 'label'}
          - {property: 'description'}
          - {property: 'tplBlockPositions', label: 'Blocks'}
      form:
        fields:
          - {property: 'label'}
          - {property: 'description'}
          - {property: 'tplBlockPositions', label: 'Blocks'}
