##################################
App\Entity\Block\Block:
  attributes:
    denormalization_context:
      groups:
        - 'Block:Update'

    normalization_context:
      groups:
        - 'Block:Read'
        - 'Resource'
        - 'Label'
        - 'Description'
      preserve_empty_objects: true
      skip_null_values: false

  collectionOperations:
    get:
      security: is_granted('ROLE_CCEUser') or is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'
    getstat:
      method: GET
      path: /blocks/stats
      security: is_granted('ROLE_CCEDashboard')
      security_message: 'Sorry, but you are not authorized.'
      normalization_context:
        groups:
          - 'Resource'
          - 'Label'
          - 'Description'
          - 'Score'
        skip_null_values: false

  itemOperations:
    get:
      security: is_granted('ROLE_CCEUser') or is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'
    getstat:
      method: GET
      path: /blocks/{id}/stats
      security: is_granted('ROLE_CCEDashboard')
      security_message: 'Sorry, but you are not authorized.'
      normalization_context:
        groups:
          - 'Resource'
          - 'Label'
          - 'Description'
          - 'Score'
    patch:
      denormalization_context:
        groups:
          - 'Block:Update'
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'

##################################
App\Entity\Calendar:
  attributes:
    denormalization_context:
      groups:
        - 'Calendar:Update'
        - 'Label'
        - 'Description'

    normalization_context:
      groups:
        - 'Calendar:Read'
        - 'Resource'
        - 'Label'
        - 'Description'
      preserve_empty_objects: true
      skip_null_values: false

  collectionOperations:
    get:
      security: is_granted('ROLE_CCEUser') or is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'
    post:
      security: is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'

  itemOperations:
    delete:
      security: is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'
    get:
      security: is_granted('ROLE_CCEUser') or is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'
    patch:
      security: is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'

##################################
App\Entity\Category:
  attributes:
    denormalization_context:
      groups:
        - 'Category:Update'
        - 'Label'
        - 'Description'

    normalization_context:
      groups:
        - 'Category:Read'
        - 'Resource'
        - 'Label'
        - 'Description'
      preserve_empty_objects: true

  collectionOperations:
    get:
      security: is_granted('ROLE_CCEUser') or is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'
    post:
      security: is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'

  itemOperations:
    delete:
      security: is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'
    get:
      security: is_granted('ROLE_CCEUser') or is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'
    patch:
      security: is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'

##################################
App\Entity\Folder\Folder:
  attributes:

    normalization_context:
      groups:
        - 'Folder:Read'
        - 'Resource'
        - 'Label'
        - 'Description'
        - 'State'
        - 'Blame'
        - 'Timestamp'
      preserve_empty_objects: true
      skip_null_values: false

  collectionOperations:
    get:
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'
    getdraft:
      method: GET
      path: /draftfolders
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'
    stats:
      method: GET
      path: /folders/stats
      security: is_granted('ROLE_CCEDashboard')
      security_message: 'Sorry, but you are not authorized.'
      normalization_context:
        groups:
          - 'Folder:Read'
          - 'Blame'
          - 'Timestamp'
          - 'Resource'
          - 'Label'
          - 'Description'
          - 'Score'
    create:
      method: POST
      input: App\Entity\Folder\Folder
      denormalization_context:
        groups:
          - 'Folder:Create'
          - 'Folder:Read'
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'

  itemOperations:
    get:
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'
    getstats:
      method: GET
      path: /folders/{id}/stats
      security: is_granted('ROLE_CCEDashboard')
      security_message: 'Sorry, but you are not authorized.'
      normalization_context:
        groups:
          - 'Blame'
          - 'Timestamp'
          - 'Resource'
          - 'Label'
          - 'Description'
          - 'Score'
    update:
      method: PATCH
      input: App\Entity\Folder\Folder
      denormalization_context:
        groups:
          - 'Folder:Read'
          - 'Folder:Update'
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'
    submit:
      method: PATCH
      input: App\Entity\Folder\Folder
      path: /folders/{id}/submit
      denormalization_context:
        groups:
          - 'none'
      normalization_context:
        groups:
          - 'Submit'
          - 'label'
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'

##################################
App\Entity\Question\Question:
  attributes:
    denormalization_context:
      groups:
        - 'Question:Update'

    normalization_context:
      groups:
        - 'Question:Read'
        - 'Resource'
        - 'Label'
        - 'Description'
      preserve_empty_objects: true
      skip_null_values: false

  collectionOperations:
    get:
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'

  itemOperations:
    get:
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'
    patch:
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'

##################################
App\Entity\Answer\Answer:
  attributes:
    denormalization_context:
      groups:
        - 'Answer:Update'

    normalization_context:
      groups:
        - 'Answer:Read'
      preserve_empty_objects: true
      skip_null_values: false

  collectionOperations:
    get:
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'
    post:
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'

  itemOperations:
    delete:
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'
    get:
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'
    patch:
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'

##################################
App\Entity\Choice\Choice:
  attributes:
    denormalization_context:
      groups:
        - 'Choice:Update'

    normalization_context:
      groups:
        - 'Choice:Read'
        - 'Resource'
      preserve_empty_objects: true
      skip_null_values: false

  collectionOperations:
    get:
      security: is_granted('ROLE_CCEUser') or is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'

  itemOperations:
    get:
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'
    patch:
      security: is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'

##################################
App\Entity\Questionnaire\Questionnaire:
  attributes:
    output: App\Entity\Questionnaire\Questionnaire
    input: App\Entity\Questionnaire\Questionnaire
    denormalization_context:
      groups:
        - 'Questionnaire:Update'
        - 'Score'
        - 'Resource'
        - 'Label'
        - 'Description'

    normalization_context:
      groups:
        - 'Blame'
        - 'Timestamp'
        - 'Questionnaire:Read'
        - 'Resource'
        - 'Label'
        - 'Description'
      preserve_empty_objects: true
      skip_null_values: false

  collectionOperations:
    get:
      security: is_granted('ROLE_CCEUser') or is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'
    getstat:
      method: GET
      path: /questionnaires/stats
      security: is_granted('ROLE_CCEDashboard')
      security_message: 'Sorry, but you are not authorized.'
      openapi_context:
        summary: 'Get questionnaires stats'
        description: ''
      normalization_context:
        groups:
          - 'Blame'
          - 'Timestamp'
          - 'Resource'
          - 'Label'
          - 'Description'
          - 'Score'
        skip_null_values: false

  itemOperations:
    get:
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'
    pdf:
      method: GET
      path: /questionnaires/{id}/pdf
      controller: App\Controller\GetQuestionnairePDFContentAction
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'
      openapi_context:
        summary: 'Get questionnaire PDF'
        description: ''
      normalization_context:
        groups:
          - 'Resource'
    sendpdf:
      method: GET
      path: /questionnaires/{id}/sendpdf
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'
      openapi_context:
        summary: 'Send questionnaire PDF'
        description: ''
        parameters:
          - name: recipients
            in: query
            description: 'list of recipients'
            required: true
            minItems: 1
            maxItems: 5
            style: deepObject
            schema:
              type: array
              collectionFormat: pipes
              items:
                type: string
      normalization_context:
        groups:
          - 'Resource'

    getstat:
      method: GET
      path: /questionnaires/{id}/stats
      security: is_granted('ROLE_CCEDashboard')
      security_message: 'Sorry, but you are not authorized.'
      openapi_context:
        summary: 'Get questionnaire stats'
        description: ''
      normalization_context:
        groups:
          - 'Blame'
          - 'Timestamp'
          - 'Resource'
          - 'Label'
          - 'Description'
          - 'Score'
    patch:
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'

##################################
App\Entity\Task:
  attributes:
    denormalization_context:
      groups:
        - 'User:Read'
        - 'Task:Update'

    normalization_context:
      groups:
        - 'User:Read'
        - 'Task:Read'
        - 'State'
        - 'Resource'
        - 'Blame'
        - 'Timestamp'
      preserve_empty_objects: true
      skip_null_values: false

    input: App\Entity\Task
    output: App\Entity\Task

  collectionOperations:
    get:
      security: is_granted('ROLE_CCEUser') or is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'
    create:
      method: POST
      security: is_granted('ROLE_CCEUser') or is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'

  itemOperations:
    delete:
      security: is_granted('ROLE_CCEUser') or is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'
    get:
      security: is_granted('ROLE_CCEUser') or is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'
    update:
      method: PATCH
      security: is_granted('ROLE_CCEUser') or is_granted('ROLE_CCEAdmin')
      security_message: 'Sorry, but you are not authorized.'
    done:
      method: PATCH
      path: /tasks/{id}/done
      denormalization_context:
        groups:
          - 'none'
      normalization_context:
        groups:
          - 'Done'
          - 'label'
      security: is_granted('ROLE_CCEUser')
      security_message: 'Sorry, but you are not authorized.'
